### ISSUE TITLE
[VMSS Terraform AVM Review PG Feedback]  #1 Structure of the module

### ISSUE THREAD

**Issue by Kanik09** [Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset#58]
### Structure of examples in AVM should be modified to match Bicep AVM's structure and should contain below:

- [ ] default-windows
- [ ] default-linux
- [ ] max-windows
- [ ] max-linux

**Comment by matt-FFFFFF** [comment]
We don't have the concept of 'max' for terraform as it's subject to interpretation.

We can provide specific use cases though.

**Comment by terrymandin** [comment]
> We don't have the concept of 'max' for terraform as it's subject to interpretation.
> 
> We can provide specific use cases though.

As per @matt-FFFFFF reply, I will remove the "max" example.  @Kanik09, if there are specific use cases you would like applied, please request them in separate issues.

**Comment by terrymandin** [comment]
Starting work on this now

**Comment by terrymandin** [comment]
As per Matt's comment I have removed the max examples, and have created two new auto-scale linux and windows examples.
![image](https://github.com/user-attachments/assets/7368ed83-d511-4046-8679-533ca13ed3fe)
