### ISSUE TITLE
[VMSS Terraform AVM Review PG Feedback] #3 AVM v0.1.2 specific feedback.

### ISSUE THREAD

**Issue by Kanik09** [Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset#60]
- [x] Scaling mode should be manual by default but AutoScale for Max. Currently, I see that this is part of default but not max. 
  - Autoscale was removed from the default example.  I created two new linux and windows auto scale examples.
![image](https://github.com/user-attachments/assets/dbfc1a76-fd30-4302-b638-3241622190b3)
- [x] VMSS should be deployed across 3 availability zones. And **zoneBalance** should be set to **false** by default. (Applicable for both default and max). Currently not set for Max module v0.1.2. 
- [x] Please ensure that the latest source image is taken for deploying VMSS. 
- [x] Ensure that customers are prompted for updating a valid port for Health extension to be enabled by default. Only then, Automatic repair policy and health monitoring should be enabled by default. (on-going conversation over email.)
  - A health extension is not default in the AVM.  If a user chooses to create a health extension, they will need to provide a port.  All examples include health extensions.
- [x] Enable <a title="Original URL: https://learn.microsoft.com/en-us/azure/virtual-machines/automatic-vm-guest-patching. Click or tap if you trust this link." href="https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fvirtual-machines%2Fautomatic-vm-guest-patching&amp;data=05%7C02%7Ckanik%40microsoft.com%7Cc9d5f5f58a8f42b02c0208dc7f35e745%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638525116734760418%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&amp;sdata=oA1jU0mYuwv6%2BaSrrA1pU9GMHzYNmkvHvQvroIR7x2Y%3D&amp;reserved=0" data-auth="Verified" data-linkindex="0" data-ogsc="">Auto Guest Patching</a>&nbsp; by default for VMSS flex. This will ensure that customers are secured when creating VMSS through ARM, PS/CLI. It is not supported on VMSS uniform currently. Patch Orchestration options should be set to Azure-orchestrated. Not set in v0.1.2 as part of default or max modules. 
- [x] Auto OS Image Upgrades should not be enabled by default as it can result in data loss for customers. 
- [x] Allocation policy should be set to Max spreading, that is, set platformFaultDomainCount = 1.

**Comment by terrymandin** [comment]
@Kanik09, will implement all of your recommendations.  As per @matt-FFFFFF [comment](https://github.com/Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset/issues/58#issuecomment-2166557384), I will be removing the "max" example, but can add your first recommendation in a new "autoscale" windows/linux examples.  

This one: "Scaling mode should be manual by default but AutoScale for Max. Currently, I see that this is part of default but not max."
