### ISSUE TITLE
[AVM Module Issue]: 

### ISSUE THREAD

**Issue by adamevoila** [Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset#64]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Hello, 
I want to ask is there any possibility to access the VM instances to configure a backup for them or an input to define a specific recovery vault? 

In the AVM VM module you have the configuration for an azure backup. My plan is it to provide the scale set also a specific recovery vault. In my project, is it necessary to have only one recovery service vault for all the machines. 

I tried to loop over all the VM instances and apply a backup setting, but in the ressource output of the scale set there is no reference to them. 

Thank you very much.

**Comment by terrymandin** [comment]
Thanks for the suggestion @adamevoila.  The underlying provider does not currently support adding backups.  I'm wondering if a better approach would be to create the VM with backup and add it to the VMSS?  I will check with our engineering teams.
