### ISSUE TITLE
[AVM Question/Feedback]: Admin password should be optional for Linux VMSS

### ISSUE THREAD

**Issue by benhurjoel** [Azure/terraform-azurerm-avm-res-compute-virtualmachinescaleset#91]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

The variable 'admin_password' should be made optional for Linux VMSS. Because of this module composition, the 'admin_password' value is always expected even SSH keys are used 

![Image](https://github.com/user-attachments/assets/34d34179-80a7-4067-b855-84bf89d3b23b)

Variable definition 

![Image](https://github.com/user-attachments/assets/fb102a52-0459-4bdc-bbd4-1d53a44decb0)

I cloned the code and made the following edit; it no longer shows the error. In my opinion, the admin password should be part of the OS Profile map, instead of being a separate variable. Please advise if I'm missing something.

```hcl
      dynamic "linux_configuration" {
        for_each = os_profile.value.linux_configuration == null ? [] : [os_profile.value.linux_configuration]

        content {
          admin_username                  = linux_configuration.value.admin_username
          admin_password                  = try(var.admin_password, null)
```

**Comment by terrymandin** [comment]
The OS password was made into a separate variable as it is sensitive to meet this requirement: [ID: TFNFR19 - Category: Code Style - Sensitive Data Variables](https://azure.github.io/Azure-Verified-Modules/specs/terraform/#id-tfnfr19---category-code-style---sensitive-data-variables).  I chose the second option and placed the password in a separate variable.

**Comment by benhurjoel** [comment]
Thank  you @terrymandin . That clarifies.
